export enum Tables {
  Plan = 'Plan',
  Subscription = 'Subscription',
  User = 'User',
  Video = 'Video',
  Movie = 'Movie',
  Content = 'Content',
  Thumbnail = 'Thumbnail',
  Episode = 'Episode',
  TvShow = 'TvShow',
  VideoMetadata = 'VideoMetadata',
  // Billing tables
  BillingAddOn = 'BillingAddOn',
  BillingCharge = 'BillingCharge',
  BillingCredit = 'BillingCredit',
  BillingDiscount = 'BillingDiscount',
  BillingDunningAttempt = 'BillingDunningAttempt',
  BillingInvoice = 'BillingInvoice',
  BillingInvoiceLineItem = 'BillingInvoiceLineItem',
  BillingPayment = 'BillingPayment',
  BillingSubscriptionAddOn = 'BillingSubscriptionAddOn',
  BillingSubscriptionDiscount = 'BillingSubscriptionDiscount',
  BillingTaxCalculationError = 'BillingTaxCalculationError',
  BillingTaxCalculationSummary = 'BillingTaxCalculationSummary',
  BillingTaxRate = 'BillingTaxRate',
  BillingUsageRecord = 'BillingUsageRecord',
  PlanChangeRequest = 'PlanChangeRequest',
}
