import { faker } from '@faker-js/faker';
import { TestingModule } from '@nestjs/testing';
import { BillingModule } from '@billingModule/billing.module';
import { ChangePlanUseCase } from '@billingModule/subscription/core/use-case/change-plan';
import { ChangePlanCommand } from '@billingModule/subscription/core/use-case/change-plan/change-plan.command';
import { PlanInterval } from '@billingModule/subscription/core/enum/plan-interval.enum';
import { SubscriptionStatus } from '@billingModule/subscription/core/enum/subscription-status.enum';
import { OutboxRepository } from '@billingModule/shared/outbox/repository/outbox.repository';
import { OutboxProcessorService } from '@billingModule/shared/outbox/processor/outbox-processor.service';
import { InvoiceRepository } from '@billingModule/invoice/persistence/repository/invoice.repository';
import { ChargeType } from '@billingModule/shared/core/enum/charge-type.enum';
import { planFactory } from '@billingModule/__test__/factory/plan.factory';
import { subscriptionFactory } from '@billingModule/__test__/factory/subscription.factory';
import { Tables } from '@testInfra/enum/table.enum';
import { testDbClient } from '@testInfra/knex.database';
import { createNestApp } from '@testInfra/test-e2e.setup';

describe('Change Plan Event Flow (Integration)', () => {
  let module: TestingModule;
  let changePlanUseCase: ChangePlanUseCase;
  let outboxRepository: OutboxRepository;
  let outboxProcessor: OutboxProcessorService;
  let invoiceRepository: InvoiceRepository;
  const userId = faker.string.uuid();

  beforeAll(async () => {
    const nestTestSetup = await createNestApp([BillingModule]);
    module = nestTestSetup.module;

    changePlanUseCase = module.get<ChangePlanUseCase>(ChangePlanUseCase);
    outboxRepository = module.get<OutboxRepository>(OutboxRepository);
    outboxProcessor = module.get<OutboxProcessorService>(
      OutboxProcessorService,
    );
    invoiceRepository = module.get<InvoiceRepository>(InvoiceRepository);
  });

  beforeEach(async () => {
    jest
      .useFakeTimers({ advanceTimers: true })
      .setSystemTime(new Date('2023-01-01'));
  });

  afterEach(async () => {
    // Clean up database
    await testDbClient('DomainEventsOutbox').delete();
    await testDbClient(Tables.BillingInvoiceLineItem).delete();
    await testDbClient(Tables.BillingInvoice).delete();
    await testDbClient(Tables.BillingCredit).delete();
    await testDbClient(Tables.BillingSubscriptionAddOn).delete();
    await testDbClient(Tables.Subscription).delete();
    await testDbClient(Tables.BillingAddOn).delete();
    await testDbClient(Tables.Plan).delete();
  });

  afterAll(async () => {
    module.close();
  });

  it('should process event and generate invoice', async () => {
    // Arrange: Create plans and subscription
    const basicPlan = planFactory.build({
      name: 'Basic',
      currency: 'USD',
      amount: 10.0,
      interval: PlanInterval.Month,
    });
    await testDbClient(Tables.Plan).insert(basicPlan);

    const premiumPlan = planFactory.build({
      name: 'Premium',
      currency: 'USD',
      amount: 20.0,
      interval: PlanInterval.Month,
    });
    await testDbClient(Tables.Plan).insert(premiumPlan);

    const subscription = subscriptionFactory.build({
      userId,
      planId: basicPlan.id,
      status: SubscriptionStatus.Active,
      currentPeriodStart: new Date('2023-01-01'),
      currentPeriodEnd: new Date('2023-02-01'),
    });
    await testDbClient(Tables.Subscription).insert(subscription);

    // Act 1: Execute change plan via Use Case
    const command = new ChangePlanCommand(
      userId,
      subscription.id!,
      premiumPlan.id!,
      undefined,
      false,
    );
    await changePlanUseCase.execute(command);

    // Assert 1: Verify event was saved in outbox
    const events = await outboxRepository.findPending(10);
    expect(events).toHaveLength(1);
    expect(events[0].eventType).toBe('subscription.plan.changed');
    expect(events[0].aggregateId).toBe(subscription.id);
    expect(events[0].published).toBe(false);

    // Act 2: Force process outbox (simulate processor)
    // Note: In a real scenario, this would be done by the scheduled processor
    // For testing, we'll manually trigger the processing
    await outboxProcessor.forceProcess();

    // Assert 2: Verify event was published
    const processedEvents = await outboxRepository.findPending(10);
    expect(processedEvents).toHaveLength(0);

    // Verify event was marked as published
    const publishedEvents = await testDbClient('DomainEventsOutbox').where({
      id: events[0].id,
    });
    expect(publishedEvents[0].published).toBe(true);
    expect(publishedEvents[0].publishedAt).toBeDefined();

    // Assert 3: Verify invoice was generated by event handler
    // Wait a bit for async processing (if needed)
    await new Promise((resolve) => setTimeout(resolve, 100));

    const invoices = await invoiceRepository.findBySubscriptionId(
      subscription.id!,
    );
    expect(invoices.length).toBeGreaterThanOrEqual(1);

    // Verify invoice has correct subscription ID
    const invoice = invoices.find(
      (inv) => inv.subscriptionId === subscription.id,
    );
    expect(invoice).toBeDefined();
    expect(invoice?.subscriptionId).toBe(subscription.id);

    // Assert 4: Verify invoice has all components (proration, usage, taxes, discounts, credits)
    expect(invoice?.invoiceLines).toBeDefined();
    expect(invoice?.invoiceLines.length).toBeGreaterThan(0);

    // Verify proration line items exist
    const prorationLines = invoice?.invoiceLines.filter(
      (line) => line.chargeType === ChargeType.Proration,
    );
    expect(prorationLines?.length).toBeGreaterThan(0);

    // Verify invoice has totals calculated (totalCredit and amountDue should be set)
    // Note: These are set by the handler after applying credits
    expect(invoice?.total).toBeDefined();
    expect(invoice?.totalCredit).toBeDefined();
    expect(invoice?.amountDue).toBeDefined();
  });

  it('should handle multiple change plan events correctly', async () => {
    // Arrange
    const plan1 = planFactory.build({
      name: 'Plan 1',
      currency: 'USD',
      amount: 10.0,
      interval: PlanInterval.Month,
    });
    await testDbClient(Tables.Plan).insert(plan1);

    const plan2 = planFactory.build({
      name: 'Plan 2',
      currency: 'USD',
      amount: 20.0,
      interval: PlanInterval.Month,
    });
    await testDbClient(Tables.Plan).insert(plan2);

    const plan3 = planFactory.build({
      name: 'Plan 3',
      currency: 'USD',
      amount: 30.0,
      interval: PlanInterval.Month,
    });
    await testDbClient(Tables.Plan).insert(plan3);

    const subscription = subscriptionFactory.build({
      userId,
      planId: plan1.id,
      status: SubscriptionStatus.Active,
      currentPeriodStart: new Date('2023-01-01'),
      currentPeriodEnd: new Date('2023-02-01'),
    });
    await testDbClient(Tables.Subscription).insert(subscription);

    // Act: Change plan twice
    const command1 = new ChangePlanCommand(userId, subscription.id!, plan2.id!);
    await changePlanUseCase.execute(command1);

    // Update subscription planId manually for second change
    await testDbClient(Tables.Subscription)
      .where({ id: subscription.id })
      .update({ planId: plan2.id });

    const command2 = new ChangePlanCommand(userId, subscription.id!, plan3.id!);
    await changePlanUseCase.execute(command2);

    // Assert: Should have 2 events
    const events = await outboxRepository.findPending(10);
    expect(events.length).toBeGreaterThanOrEqual(2);

    // Process events
    await outboxProcessor.forceProcess();

    // Verify all events were processed
    const remainingEvents = await outboxRepository.findPending(10);
    expect(remainingEvents).toHaveLength(0);
  });
});
